apiVersion: apps/v1
kind: Deployment
metadata:
  name: org2-ca
  labels: {
    component: org2,
    type: ca
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: org2
      type: ca
  template:
    metadata:
      labels:
        component: org2
        type: ca
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: org2-ca
          image: hyperledger/fabric-ca:1.4.7
          command: ["sh"]
          args: ["/scripts/start-root-ca.sh"]
          ports:
            - containerPort: 7054
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: USERNAME
              value: admin
            - name: PASSWORD
              value: adminpw
            - name: CSR_HOSTS
              value: org2-ca
          volumeMounts:
            - mountPath: /scripts
              name: my-pv-storage
              subPath: files/scripts
            - mountPath: /etc/hyperledger/fabric-ca-server
              name: my-pv-storage
              subPath: state/org2-ca
