apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-oracle-couchdb-deployment
  labels: {
    component: peer0,
    type: couchdb,
    org: oracle
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peer0
      type: couchdb
      org: oracle
  template:
    metadata:
      labels:
        component: peer0
        type: couchdb
        org: oracle
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: peer0-oracle-couchdb
          image: couchdb:3.1.1
          env:
            - name: COUCHDB_USER
              value: nick
            - name: COUCHDB_PASSWORD
              value: "1234"
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: my-pv-storage
              subPath: state/oracle/peers/peer0-couchdb
