apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-peer1-hp-deployment
  labels: {
    component: peer1,
    type: cli,
    org: hp
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peer1
      type: cli
      org: hp
  template:
    metadata:
      labels:
        component: peer1
        type: cli
        org: hp
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: peer1-hp
          image: hyperledger/fabric-tools:2.2.1
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: ["sleep"]
          args: ["infinity"]
          env:
            - name: GOPATH
              value: /opt/gopath
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_PEER_ID
              value: cli-peer1-hp
            - name: CORE_PEER_ADDRESS
              value: peer1-hp-service:7051
            - name: CORE_PEER_LOCALMSPID
              value: hp
            - name: CORE_PEER_MSPCONFIGPATH
              value: /etc/hyperledger/fabric/msp/users/Admin@hp/msp
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/tls/ca.crt
          volumeMounts:
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
              name: my-pv-storage
              subPath: files/orderer
            - mountPath: /opt/gopath/src/resources
              name: my-pv-storage
              subPath: files/chaincode/resources
            - mountPath: /opt/gopath/src/resource_types
              name: my-pv-storage
              subPath: files/chaincode/resource_types
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channels
              name: my-pv-storage
              subPath: files/channels
            - mountPath: /etc/hyperledger/fabric/msp
              name: my-pv-storage
              subPath: files/crypto-config/peerOrganizations/hp
            - mountPath: /etc/hyperledger/fabric/tls
              name: my-pv-storage
              subPath: files/crypto-config/peerOrganizations/hp/peers/peer1-hp/tls
            - mountPath: /etc/hyperledger/orderers
              name: my-pv-storage
              subPath: files/crypto-config/ordererOrganizations/orderer

