apiVersion: v1
kind: Service
metadata:
  name: peer0-hp-service
  labels: {
    component: peer0,
    type: peer,
    org: hp
  }
spec:
  type: ClusterIP
  selector:
    component: peer0
    type: peer
    org: hp
  ports:
    - port: 7051
      targetPort: 7051
---
apiVersion: v1
kind: Service
metadata:
  name: peer1-hp-service
  labels: {
    component: peer1,
    type: peer,
    org: hp
  }
spec:
  type: ClusterIP
  selector:
    component: peer1
    type: peer
    org: hp
  ports:
    - port: 7051
      targetPort: 7051
