version: '2'

networks:
  fabric-ca:

services:
  # Servers
  orderers-ca:
    image: hyperledger/fabric-ca:1.4.7
    container_name: orderers-ca
    ports:
      - 7054:7054
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - USERNAME=admin
      - PASSWORD=adminpw
      - CSR_HOSTS=orderers-ca
    volumes:
      - ../../state/ca/orderers/server:/etc/hyperledger/fabric-ca-server
      - ../../scripts:/scripts
    command: sh -c '/scripts/start-root-ca.sh'
    networks:
      - fabric-ca
  ibm-ca:
    image: hyperledger/fabric-ca:1.4.7
    container_name: ibm-ca
    ports:
      - 7055:7054
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - USERNAME=admin
      - PASSWORD=adminpw
      - CSR_HOSTS=ibm-ca
    volumes:
      - ../../state/ca/ibm/server:/etc/hyperledger/fabric-ca-server
      - ../../scripts:/scripts
    command: sh -c '/scripts/start-root-ca.sh'
    networks:
      - fabric-ca
  oracle-ca:
    image: hyperledger/fabric-ca:1.4.7
    container_name: oracle-ca
    ports:
      - 7056:7054
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - USERNAME=admin
      - PASSWORD=adminpw
      - CSR_HOSTS=oracle-ca
    volumes:
      - ../../state/ca/oracle/server:/etc/hyperledger/fabric-ca-server
      - ../../scripts:/scripts
    command: sh -c '/scripts/start-root-ca.sh'
    networks:
      - fabric-ca
  # Clients
  orderers-client:
    tty: true
    image: hyperledger/fabric-ca:1.4.7
    container_name: orderers-client
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CA_SCHEME=https
      - CA_URL=orderers-ca:7054
      - CA_USERNAME=admin
      - CA_PASSWORD=adminpw
      - CA_CERT_PATH=/etc/hyperledger/fabric-ca-server/tls-cert.pem
    volumes:
      - ../../state/ca/orderers/client:/etc/hyperledger/fabric-ca-client
      - ../../scripts:/scripts
      - ../../state/ca/orderers/server:/etc/hyperledger/fabric-ca-server
      - ../../crypto-config:/etc/hyperledger/fabric-ca/crypto-config
    command: sh -c '/scripts/start-orderer-client.sh'
    networks:
      - fabric-ca
    depends_on:
      - orderers-ca
  ibm-client:
    tty: true
    image: hyperledger/fabric-ca:1.4.7
    container_name: ibm-client
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - ORG_NAME=ibm
      - CA_SCHEME=https
      - CA_URL=ibm-ca:7054
      - CA_USERNAME=admin
      - CA_PASSWORD=adminpw
      - CA_CERT_PATH=/etc/hyperledger/fabric-ca-server/tls-cert.pem
    volumes:
      - ../../state/ca/ibm/client:/etc/hyperledger/fabric-ca-client
      - ../../scripts:/scripts
      - ../../state/ca/ibm/server:/etc/hyperledger/fabric-ca-server
      - ../../crypto-config:/etc/hyperledger/fabric-ca/crypto-config
    command: sh -c '/scripts/start-org-client.sh'
    networks:
      - fabric-ca
    depends_on:
      - ibm-ca
  oracle-client:
    tty: true
    image: hyperledger/fabric-ca:1.4.7
    container_name: oracle-client
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - ORG_NAME=oracle
      - CA_SCHEME=https
      - CA_URL=oracle-ca:7054
      - CA_USERNAME=admin
      - CA_PASSWORD=adminpw
      - CA_CERT_PATH=/etc/hyperledger/fabric-ca-server/tls-cert.pem
    volumes:
      - ../../state/ca/oracle/client:/etc/hyperledger/fabric-ca-client
      - ../../scripts:/scripts
      - ../../state/ca/oracle/server:/etc/hyperledger/fabric-ca-server
      - ../../crypto-config:/etc/hyperledger/fabric-ca/crypto-config
    command: sh -c '/scripts/start-org-client.sh'
    networks:
      - fabric-ca
    depends_on:
      - oracle-ca
