apiVersion: v1
kind: Service
metadata:
  name: peer0-ibm-couchdb
  labels: {
    component: peer0,
    type: couchdb,
    org: ibm
  }
spec:
  type: ClusterIP
  selector:
    component: peer0
    type: couchdb
    org: ibm
  ports:
    - port: 5984
      targetPort: 5984
---
apiVersion: v1
kind: Service
metadata:
  name: peer1-ibm-couchdb
  labels: {
    component: peer1,
    type: couchdb,
    org: ibm
  }
spec:
  type: ClusterIP
  selector:
    component: peer1
    type: couchdb
    org: ibm
  ports:
    - port: 5984
      targetPort: 5984
